/** Editorial content pages: disciplined page heroes, process rails, evidence-led cards, and public-safe copy. */
import { ArrowRight, ArrowUpRight, Check, Download, Mail, MapPin, ShieldCheck } from "lucide-react";
import { FormEvent } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

const PDF = "/assets/documents/athoth-capability-statement.pdf";

function PageHero({ eyebrow, title, lead, image, children }: { eyebrow:string; title:string; lead:string; image?:string; children?:React.ReactNode }) {
  return <section className="page-hero"><div className="container page-hero-grid"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{lead}</p>{children && <div className="actions">{children}</div>}</div>{image && <div className="page-hero-image"><img src={image} alt="" /><span>ATH / RESEARCH SYSTEMS</span></div>}</div></section>;
}

function CTA({ eyebrow, title, label = "Start a conversation" }: { eyebrow:string; title:string; label?:string }) { return <section className="cta-section"><div className="container cta-panel"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><Link className="button button-primary" href="/contact">{label} <ArrowRight size={17}/></Link></div></section>; }

export function Research() {
  const areas = [["Professional skill representations","Formal structures for triggers, goals, intervention strategies, adaptation rules, outcomes, evidence, provenance, and governance."],["Demonstration-to-skill learning","Methods that transform expert episodes into reusable skill abstractions rather than storing only transcripts or trajectories."],["Governed agentic systems","Confidence-aware decision gates, policy overlays, human review, auditing, rollback, and escalation."],["Outcome-grounded adaptation","Continual refinement based on measured results, counterexamples, and expert validation."]];
  return <main><PageHero eyebrow="Athoth research" title="Learning systems built around professional expertise." lead="Our emerging research examines how AI agents can learn from authentic expert practice while remaining transparent, governable, and subject to human authority." image="/assets/images/research-field.webp" />
    <section className="section"><div className="container narrow"><span className="eyebrow">Observational Agent Learning</span><h2>Learning the logic behind expert action.</h2><div className="claim"><ShieldCheck/><p><strong>Responsible research claim.</strong> OAL is being developed and evaluated as a candidate computational learning framework. Its status as a distinct paradigm depends on formal specification, implementation, comparison, and empirical validation.</p></div><p className="large-copy">Learning from observation is not new. Athoth’s research instead focuses on the proposed learned object: a structured representation of professional skill that includes when an intervention applies, the recipient state, expert goal, rationale, expected outcomes, provenance, confidence, policy constraints, and escalation conditions.</p></div></section>
    <section className="section section-mist"><div className="container editorial-split"><div><span className="eyebrow">Research commitments</span><h2>Human authority is architectural.</h2></div><ul className="commitment-list">{["Experts teach through authentic work rather than translating everything into prompts or scripts.","Systems infer context, intent, and applicability—not merely reproduce behavior.","Skills remain inspectable, attributable, versioned, and open to expert correction.","Outcomes and safe transfer matter more than surface imitation.","Human professionals retain authority over high-impact decisions."].map(x=><li key={x}><Check/>{x}</li>)}</ul></div></section>
    <section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Research areas</span><h2>A disciplined path from demonstration to skill.</h2></div></div><div className="research-area-grid">{areas.map(([t,c],i)=><article key={t}><b>0{i+1}</b><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
    <section className="section research-band"><div className="container"><span className="eyebrow light">Research pathway</span><h2>From hypothesis to evidence.</h2><div className="stage-grid">{[["01","Formalize","Define OAL boundaries, terminology, conformance levels, and falsifiable hypotheses."],["02","Prototype","Build a transcript-first demonstration-to-skill system for a bounded tutoring domain."],["03","Validate","Compare against prompting, retrieval, imitation, and intent-aware baselines using transfer, safety, and outcome measures."]].map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section><CTA eyebrow="Research partnerships" title="Collaborate on OAL research and evaluation." label="Discuss a partnership" /></main>;
}

export function Capabilities() {
  const cards = [["Applied AI research","Research design, literature synthesis, formalization, experimental protocols, benchmarks, and peer-review-ready technical documentation."],["Agentic system architecture","Human-in-the-loop agents, workflow orchestration, tool use, memory, decision gates, provenance, evaluation, and escalation."],["Machine learning and data science","Predictive modeling, causal analysis, multimodal data integration, NLP, analytics, model validation, and reproducible pipelines."],["Secure AI and cybersecurity","Controlled test environments, defensive automation, logging, risk analysis, policy constraints, and responsible AI assurance."],["Learning and workforce systems","Adaptive learning, mentoring, advising, workforce readiness, professional development, and institutional knowledge transfer."],["Research commercialization","Feasibility assessment, prototype planning, IP-oriented technical documentation, product strategy, and government proposal development."]];
  const stages = [["Discovery","Problem framing, stakeholder analysis, constraints, data and risk assessment","Research and system requirements brief"],["Formalization","Scientific model, architecture, terminology, measures, and hypotheses","Technical specification and evaluation plan"],["Prototype","Rapid implementation using fit-for-purpose models and secure infrastructure","Minimum viable system and test harness"],["Validation","Baselines, ablations, outcome measures, safety and governance testing","Evidence package and technical report"],["Transition","Deployment planning, training, monitoring, knowledge transfer, and sustainment","Operational roadmap and implementation support"]];
  return <main><PageHero eyebrow="Capabilities" title="Research depth with an operational path." lead="Athoth helps clients move from complex AI questions to formal models, working prototypes, evaluation evidence, and responsibly deployed systems." image="/assets/images/capability-system.webp"><a className="button button-primary" href={PDF} target="_blank" rel="noreferrer">Capability statement <Download size={17}/></a></PageHero><section className="section"><div className="container"><div className="service-grid">{cards.map(([t,c],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section><section className="section section-mist"><div className="container"><span className="eyebrow">How we work</span><h2>Research → prototype → evidence → deployment.</h2><div className="process-table"><div className="process-row head"><span>Stage</span><span>Athoth contribution</span><span>Typical output</span></div>{stages.map(r=><div className="process-row" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span></div>)}</div></div></section><CTA eyebrow="Need a tailored capability brief?" title="Tell us the mission and operating environment." label="Request a briefing" /></main>;
}

export function Projects() {
  const projects = [
    {label:"Learning + mentoring",title:"Adaptive learning and professional support",copy:"Research and prototype development for human-centered systems that adapt learning resources, preserve mentor judgment, structure feedback, and evaluate progress through complex academic or professional work.",tags:["Adaptive learning","Mentoring","Human-centered AI","Evaluation"],image:"/assets/images/project-adaptive-learning.png",alt:"Athoth research graphic showing adaptive learning and professional support workflows",kind:"graphic"},
    {label:"AI + data systems",title:"Machine learning and decision-support platforms",copy:"Applied data science, multimodal integration, cloud analytics, and documented decision-support workflows that turn complex information into reviewable evidence for accountable human decisions.",tags:["Machine learning","Data engineering","Cloud systems","Decision support"],image:"/assets/images/project-ai-data.png",alt:"Athoth research graphic showing machine-learning and decision-support system components",kind:"graphic"},
    {label:"Cyber + resilience",title:"Secure and resilient technology research",copy:"Controlled-environment research in defensive cybersecurity and agentic automation, designed around human authorization, auditable logging, system validation, and operational resilience.",tags:["Cybersecurity","Agentic AI","Human approval","Auditability"],image:"/assets/images/project-cyber-resilience.png",alt:"Athoth research graphic showing secure and resilient technology research controls",kind:"graphic"},
    {label:"Institutions + workforce",title:"Institutional knowledge and workforce capability",copy:"Research and technology support that preserve mission-critical knowledge, strengthen workforce readiness, and maintain accountable continuity across institutional and professional transitions.",tags:["Knowledge preservation","Workforce development","Research operations"],image:"/assets/images/project-institutional-workforce.jpeg",alt:"A mentor guiding learners during a collaborative professional development session",kind:"photo"}
  ] as const;
  return <main className="projects-page"><PageHero eyebrow="Selected experience" title="Work organized around human capability and accountable technology." lead="These public-safe summaries illustrate Athoth’s project themes without disclosing client-confidential methods, data, security details, or intellectual property." /><section className="section projects-section"><div className="container project-list">{projects.map(({label,title,copy,tags,image,alt,kind},i)=><article className="project-row" key={title}><figure className={`project-visual project-visual-${kind}`}><div className="project-index"><span>0{i+1}</span><small>{label}</small></div><div className="project-image-frame" data-plate={`ATH / EVIDENCE PLATE 0${i+1}`}><img src={image} alt={alt} loading="lazy" /></div></figure><div className="project-copy"><span className="public-badge">Public summary</span><h2>{title}</h2><p>{copy}</p><div className="tag-row">{tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section><section className="section research-band"><div className="container editorial-split"><div><span className="eyebrow light">Disclosure discipline</span><h2>Credible in public.<br />Controlled by design.</h2></div><div><p className="large-copy muted-light">Athoth classifies project information as Public, Public Summary Only, Controlled, or Confidential/IP Pending before release.</p><Link className="button button-light" href="/contact">Request relevant experience <ArrowRight size={17}/></Link></div></div></section></main>;
}

export function Government() {
  const mission = [["AI research and prototyping","Feasibility studies, system architecture, applied research, proof-of-concept development, and technical evaluation."],["Institutional knowledge continuity","Methods and tools for preserving mission knowledge, supporting succession, and reducing expertise loss."],["Workforce learning and readiness","Adaptive training, mentoring, professional development, and human-AI collaboration."],["Secure agentic systems","Controlled tool use, validation checkpoints, provenance, logging, policy constraints, and escalation."],["Data and decision intelligence","Data integration, analytics, machine learning, causal methods, and decision-support evidence."],["Responsible AI assurance","Evaluation plans, risk analysis, transparency, human oversight, performance monitoring, and governance design."]];
  return <main><PageHero eyebrow="Government + public mission" title="Accountable AI for mission-critical knowledge." lead="Athoth helps agencies and public institutions explore, prototype, evaluate, and transition AI systems that preserve expertise, strengthen workforce capability, and operate within defined policy and human-authority boundaries." image="/assets/images/governance-field.webp"><a className="button button-primary" href={PDF} target="_blank" rel="noreferrer">Capability statement <Download size={17}/></a><Link className="button button-secondary" href="/contact">Teaming inquiry</Link></PageHero><section className="section"><div className="container"><span className="eyebrow">Mission support areas</span><h2>Technical capability aligned to public purpose.</h2><div className="service-grid">{mission.map(([t,c],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section><section className="section section-mist"><div className="container editorial-split"><div><span className="eyebrow">Why Athoth</span><h2>Full-lifecycle technical depth.</h2><p>Athoth combines artificial intelligence, data science, cybersecurity, education, institutional operations, and applied research.</p></div><div className="stacked-cards"><article><ShieldCheck/><h3>Human authority</h3><p>Systems designed to support authorized professionals rather than obscure or replace accountability.</p></article><article><Check/><h3>Evidence oriented</h3><p>Comparative baselines, measurable outcomes, documentation, and reproducibility built into the research plan.</p></article></div></div></section><section className="section"><div className="container statement-panel"><div><span className="eyebrow light">Contracting information</span><h2>Ready to support qualified partners and public missions.</h2><p>Athoth Innovations LLC is headquartered in Little Rock, Arkansas. Verified contracting identifiers and representations are available directly to qualified partners and contracting officials.</p></div><Link className="button button-light" href="/contact">Request contracting details <ArrowRight size={17}/></Link></div></section></main>;
}

export function About() {
  const values=[["Human-centered","Technology should extend professional capacity and improve human outcomes."],["Evidence-driven","Claims should be tested against strong baselines and measurable results."],["Governed by design","Provenance, policy, uncertainty, review, and escalation should be architectural—not afterthoughts."],["Mission aware","Solutions must fit the organization, people, risk environment, and operating context."],["Interdisciplinary","The hardest AI problems require technical, behavioral, educational, and institutional understanding."],["Intellectually honest","We distinguish established evidence, plausible extensions, and hypotheses that still require validation."]];
  const team=[
    {name:"Jessie Walker, PhD",role:"Founder",portrait:"jessie",image:"/assets/team/jessie-walker.png",bio:"Jessie directs Athoth’s research agenda and the development of accountable AI systems centered on professional expertise, human authority, and measurable outcomes.",email:"jjw@athoth.com",linkedin:"https://linkedin.com/in/jessiejwalker",orcid:"https://orcid.org/0000-0002-8196-5474"},
    {name:"Macus Jordan",role:"Software Engineer",portrait:"macus",image:"/assets/team/macus-jordan.webp",bio:"Macus builds research prototypes and production-minded software that translate Athoth’s technical models into secure, inspectable, and useful systems.",email:"info@athoth.com"},
    {name:"Felicia Collins",role:"AI Engineer",portrait:"felicia",image:"/assets/team/felicia-collins.webp",bio:"Felicia develops and evaluates AI workflows with an emphasis on reliable behavior, evidence-driven iteration, and responsible human-AI collaboration.",email:"info@athoth.com"}
  ];
  return <main><PageHero eyebrow="About Athoth" title="Building AI around human judgment." lead="Athoth Innovations is an applied artificial intelligence research and development company focused on the computational acquisition, preservation, governance, and responsible application of professional expertise." image="/assets/images/knowledge-continuity.webp" />
    <section className="section section-mist"><div className="container editorial-split"><div><span className="eyebrow">Our direction</span><h2>Preserve what experts know. Extend what people can do. Keep humans accountable.</h2></div><p className="large-copy">Athoth’s work grew from experience at the intersection of AI, education, cybersecurity, data systems, and institutional innovation. Across those domains, one problem repeatedly emerged: critical expertise often lives in people rather than durable systems.</p></div></section>
    <section className="section team-section"><div className="container"><div className="team-heading"><div><span className="eyebrow">The people behind the work</span><h2>A small team built for consequential problems.</h2></div><p>Athoth combines research direction, AI engineering, and software delivery in one focused interdisciplinary group.</p></div><div className="team-grid">{team.map((member,i)=><article className="team-card" key={member.name}><div className={`team-portrait team-portrait-${member.portrait}`}><img src={member.image} alt={`${member.name}, ${member.role}`} /><span>ATH / 0{i+1}</span></div><div className="team-card-content"><span className="team-kicker">{member.role}</span><h3>{member.name}</h3><p>{member.bio}</p><div className="team-links"><a href={`mailto:${member.email}`} aria-label={`Email ${member.name}`}><Mail size={15}/>{member.email}</a>{member.linkedin&&<a href={member.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a>}{member.orcid&&<a href={member.orcid} target="_blank" rel="noreferrer">ORCID <ArrowUpRight size={14}/></a>}</div></div></article>)}</div></div></section>
    <section className="section"><div className="container"><div className="value-grid">{values.map(([t,c],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section><CTA eyebrow="Partner with us" title="Research, prototype, evaluate, and transition." label="Contact Athoth" /></main>;
}

export function Contact() {
  function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); const data=new FormData(e.currentTarget); const subject=encodeURIComponent(`Athoth inquiry: ${data.get("interest")}`); const body=encodeURIComponent(`Name: ${data.get("name")}\nOrganization: ${data.get("organization")}\nEmail: ${data.get("email")}\n\n${data.get("message")}`); toast.success("Your email application is opening with the inquiry details."); window.location.href=`mailto:contact@athoth.com?subject=${subject}&body=${body}`; }
  return <main><PageHero eyebrow="Contact" title="Let’s define the right problem." lead="Talk with Athoth about applied AI research, OAL partnerships, government teaming, technical prototypes, knowledge-preservation initiatives, or responsible AI strategy." /><section className="section"><div className="container contact-layout"><aside><span className="eyebrow">Partnership areas</span><h2>Make expertise more durable.</h2><p>Research collaborations, public-sector R&D, subcontracting and teaming, pilot projects, academic partnerships, and technology-transition planning.</p><div className="contact-detail"><MapPin/><span>Little Rock, Arkansas</span></div><a className="contact-detail" href="mailto:contact@athoth.com"><Mail/><span>contact@athoth.com</span></a></aside><form className="contact-form" onSubmit={submit}><div className="intake-head"><span>ATH / PARTNERSHIP INTAKE</span><div><b>01</b> Context <i></i><b>02</b> Mission <i></i><b>03</b> Response</div></div><div className="field-row"><label>Name<input name="name" required autoComplete="name" /></label><label>Organization<input name="organization" autoComplete="organization" /></label></div><label>Email<input type="email" name="email" required autoComplete="email" /></label><label>Area of interest<select name="interest" defaultValue="Research collaboration"><option>Research collaboration</option><option>Government teaming</option><option>AI prototype or pilot</option><option>Capability briefing</option><option>Other</option></select></label><label>How can we help?<textarea name="message" required /></label><button className="button button-primary" type="submit">Prepare inquiry <ArrowUpRight size={17}/></button><p className="form-note">Submitting prepares an email in your default mail application; this website does not store your message.</p></form></div></section></main>;
}

export function Privacy() { return <main><PageHero eyebrow="Company" title="Privacy" lead="How Athoth Innovations handles information associated with this website." /><section className="section"><div className="container policy"><p className="policy-date">Last updated: July 2026</p><h2>Information you choose to provide</h2><p>This website does not directly store contact-form submissions. The inquiry form prepares a message in your default email application, and any information you send is handled through your chosen email provider and Athoth’s business email systems.</p><h2>Basic website analytics</h2><p>We may receive limited technical information such as page views, approximate device type, and referral source to understand site performance. We do not use this site to sell personal information or create advertising profiles.</p><h2>External resources</h2><p>Links to downloadable documents or third-party services may be governed by their own privacy practices. Review those policies before providing information.</p><h2>Contact</h2><p>Questions about this notice can be sent to <a href="mailto:contact@athoth.com">contact@athoth.com</a>.</p></div></section></main>; }
